---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: 309705700864.dkr.ecr.us-east-1.amazonaws.com/sql_ecr:latest
      env:
        - name: MYSQL_DATABASE_USER
          valuesFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_DATABASE_USER
        - name: MYSQL_DATABASE_PASSWORD
          valuesFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_DATABASE_PASSWORD
        - name: MYSQL_DATABASE_DB
          valuesFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE_DB
        - name: MYSQL_DATABASE_HOST
          valuesFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE_HOST
      ports:
      - containerPort: 3306
        name: db-container
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
    volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: db
  type: ClusterIP